# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - globalSolution2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_b624f97da66e43b4a5e774b378ccaa08 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_4c4dbe8d65244b09a39ddcb48eb577d9 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_b624f97da66e43b4a5e774b378ccaa08 }}/globalsolution2:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'globalSolution2'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_f4be70bdb597467bbb92388dd32bb181 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_b624f97da66e43b4a5e774b378ccaa08 }}/globalsolution2:${{ github.sha }}'